import type React from 'react';
import {createContext,useContext,useEffect,useMemo,useState} from 'react';
import {getCompanions,getInventory,saveProgress,useInventoryItem} from '../api';
import type {Companion,InventoryItem} from '../game';
import {quests,starterCompanions,starterInventory} from '../game';
type DiceRoll={sides:number;result:number};
type CombatStage='idle'|'hit'|'damage'|'done';
type GameContextValue={quest:any;questIndex:number;hp:number;xp:number;level:number;dice:number|null;diceHistory:DiceRoll[];chosen:string[];log:string[];hint:boolean;inventory:InventoryItem[];companions:Companion[];solved:boolean;inventoryUseMode:boolean;usedItem:InventoryItem|null;combatStage:CombatStage;roll:(sides?:number)=>void;rollCombat:()=>void;startInventoryUse:()=>void;selectItemForUse:(item:InventoryItem)=>void;act:(action:string)=>void;wrong:()=>void;next:()=>void;toggleHint:()=>void;useItem:(id:string)=>void;heal:(amount:number)=>void;addLog:(message:string)=>void};
const GameContext=createContext<GameContextValue|null>(null);
const damageSides:Record<string,number>={dagger:4,shortsword:6,torch:4,mana_scroll:6};
export function GameProvider({children}:{children:React.ReactNode}){const[questIndex,setQuestIndex]=useState(0),[hp,setHp]=useState(100),[xp,setXp]=useState(0),[dice,setDice]=useState<number|null>(null),[diceHistory,setDiceHistory]=useState<DiceRoll[]>([]),[chosen,setChosen]=useState<string[]>([]),[log,setLog]=useState<string[]>([]),[hint,setHint]=useState(false),[inventory,setInventory]=useState(starterInventory),[companions,setCompanions]=useState(starterCompanions),[solved,setSolved]=useState(false),[inventoryUseMode,setInventoryUseMode]=useState(false),[usedItem,setUsedItem]=useState<InventoryItem|null>(null),[combatStage,setCombatStage]=useState<CombatStage>('idle');
useEffect(()=>{getInventory().then(items=>setInventory(items.map(x=>({id:String(x.id),item_key:x.item_key,name:x.name,icon:x.icon,count:x.quantity,description:x.description??''})))).catch(()=>{});getCompanions().then(items=>setCompanions(items.map(x=>({id:String(x.id),name:x.name,role:x.role,emoji:x.emoji,description:x.description??'',hp:x.hp})))).catch(()=>{})},[]);
useEffect(()=>{const refresh=()=>{getInventory().then(items=>setInventory(items.map(x=>({id:String(x.id),item_key:x.item_key,name:x.name,icon:x.icon,count:x.quantity,description:x.description??''})))).catch(()=>{})};window.addEventListener('dnd-inventory-updated',refresh);return()=>window.removeEventListener('dnd-inventory-updated',refresh)},[]);
const quest=quests[questIndex];const level=Math.max(1,Math.floor(xp/250)+1);const add=(s:string)=>setLog(x=>[s,...x].slice(0,20));
const heal=(amount:number)=>setHp(h=>Math.min(100,h+amount));const addLog=(message:string)=>add(message);
const roll=(sides=20)=>{const n=Math.floor(Math.random()*sides)+1;setDice(n);setDiceHistory(x=>[{sides,result:n},...x].slice(0,10));if(n===1&&sides===20)setHp(h=>Math.max(0,h-8));if(n===20&&sides===20)setXp(x=>x+20)};
const rollCombat=()=>{if(!usedItem||combatStage==='idle'||combatStage==='done')return;if(combatStage==='hit'){const n=Math.floor(Math.random()*20)+1;setDice(n);setDiceHistory(x=>[{sides:20,result:n},...x].slice(0,10));if(n>=10){setCombatStage('damage');add(`🎯 Попадание: d20 = ${n}. Бросайте кубик на урон.`)}else{setCombatStage('done');add(`✗ Промах: d20 = ${n}. Атака ${usedItem.name} не попала.`)}}else if(combatStage==='damage'){const sides=damageSides[usedItem.item_key]??4;const n=Math.floor(Math.random()*sides)+1;setDice(n);setDiceHistory(x=>[{sides,result:n},...x].slice(0,10));setCombatStage('done');add(`⚔ Урон ${usedItem.name}: d${sides} = ${n}.`)}};
const startInventoryUse=()=>{setInventoryUseMode(true);setUsedItem(null);setCombatStage('idle');add('🎒 Выбери предмет в инвентаре для использования.')};
const selectItemForUse=(item:InventoryItem)=>{setInventoryUseMode(false);setUsedItem(item);setCombatStage('hit');add(`🎒 Выбран предмет "${item.name}".`)};
const act=(action:string)=>{if(solved||chosen.includes(action))return;const next=[...chosen,action];setChosen(next);add(`⚔ ${action}`);if(next.length===quest.actions.length){setSolved(true);setXp(x=>x+quest.points);setHp(h=>Math.min(100,h+10));saveProgress(quest.id,true,quest.points).catch(()=>{})}};
const wrong=()=>{if(!solved){setHp(h=>Math.max(0,h-20));add(`☠ ${quest.wrong}`)}};
const next=()=>{setQuestIndex(i=>(i+1)%quests.length);setSolved(false);setChosen([]);setHp(100);setHint(false);setDice(null);setLog([]);setInventoryUseMode(false);setUsedItem(null);setCombatStage('idle')};
const useItem=(id:string)=>{const item=inventory.find(x=>x.id===id);if(!item||item.count<=0)return;useInventoryItem(item.item_key).then(()=>{setInventory(items=>items.map(x=>x.id===id?{...x,count:x.count-1}:x));if(item.item_key==='potion')heal(20)}).catch(()=>{})};
const value=useMemo(()=>({quest,questIndex,hp,xp,level,dice,diceHistory,chosen,log,hint,inventory,companions,solved,inventoryUseMode,usedItem,combatStage,roll,rollCombat,startInventoryUse,selectItemForUse,act,wrong,next,toggleHint:()=>setHint(v=>!v),useItem,heal,addLog}),[quest,questIndex,hp,xp,level,dice,diceHistory,chosen,log,hint,inventory,companions,solved,inventoryUseMode,usedItem,combatStage]);return <GameContext.Provider value={value}>{children}</GameContext.Provider>}
export function useGame(){const ctx=useContext(GameContext);if(!ctx)throw new Error('useGame must be used inside GameProvider');return ctx}
