export type Character={name:string;race:string;class:string;background:string;stats:{strength:number;dexterity:number;constitution:number;intelligence:number;wisdom:number;charisma:number}};
export type User={id:number;username:string;email:string;xp:number;streak:number;gold:number;created_at:string;avatar_url?:string|null;character?:Character|null};
export type InventoryItem={id:number;item_key:string;name:string;icon:string;quantity:number;description?:string|null};
export type ShopItem={item_key:string;name:string;icon:string;price:number;description:string;category:string};
export type ShopResponse={gold:number;items:ShopItem[]};
export type ShopBuyResponse={gold:number;inventory:InventoryItem[]};
export type Companion={id:number;name:string;role:string;emoji:string;description?:string|null;hp:number};
export type ChatMessage={id:number;role:'user'|'assistant';content:string;created_at:string};
export type DndSheet={character:Character;derived:{level:number;proficiency_bonus:number;ability_modifiers:Record<string,number>;saving_throw_proficiencies:string[];saving_throws:Record<string,number>;skill_proficiencies:string[];skills:Record<string,{name:string;ability:string;modifier:number;proficient:boolean}>;initiative:number;armor_class:number;max_hp:number;passive_perception:number}};
export type DndCheck={skill:string;skill_name:string;ability:string;roll:number;ability_modifier:number;proficiency_bonus:number;total:number;dc:number;success:boolean;critical:boolean;critical_failure:boolean;level:number};
export type DndRoll={kind:'skill'|'save'|'attack'|'damage';key:string;name:string;ability?:string;roll:number;rolls?:number[];modifier?:number;proficiency?:number;total:number;target?:number;success?:boolean;critical?:boolean;critical_failure?:boolean;damage_die?:number;ability_modifier?:number};
const TOKEN_KEY='devops_survival_token';
export const token=()=>localStorage.getItem(TOKEN_KEY);export const logout=()=>localStorage.removeItem(TOKEN_KEY);
async function request<T>(path:string,options:RequestInit={}):Promise<T>{const headers=new Headers(options.headers);if(!(options.body instanceof FormData))headers.set('Content-Type','application/json');const t=token();if(t)headers.set('Authorization',`Bearer ${t}`);const res=await fetch(path,{...options,headers});const data=await res.json().catch(()=>({detail:'Server returned invalid JSON'}));if(!res.ok)throw new Error(data.detail||`HTTP ${res.status}`);return data}
export async function register(username:string,email:string,password:string){const data=await request<{access_token:string;user:User}>('/api/auth/register',{method:'POST',body:JSON.stringify({username,email,password})});localStorage.setItem(TOKEN_KEY,data.access_token);return data.user}
export async function login(loginValue:string,password:string){const data=await request<{access_token:string;user:User}>('/api/auth/login',{method:'POST',body:JSON.stringify({login:loginValue,password})});localStorage.setItem(TOKEN_KEY,data.access_token);return data.user}
export const me=()=>request<User>('/api/auth/me');export const profile=()=>request<{user:User;progress:any[]}>('/api/profile');export const leaderboard=()=>request<{rank:number;username:string;xp:number;streak:number}[]>('/api/leaderboard');export const saveProgress=(incident_id:string,solved:boolean,score:number)=>request('/api/progress',{method:'POST',body:JSON.stringify({incident_id,solved,score})});export const getInventory=()=>request<InventoryItem[]>('/api/inventory');export const useInventoryItem=(item_key:string)=>request<{inventory:InventoryItem[]}>(`/api/inventory/use/${encodeURIComponent(item_key)}`,{method:'POST'});export const getShop=()=>request<ShopResponse>('/api/shop');export const buyShopItem=(item_key:string)=>request<ShopBuyResponse>('/api/shop/buy',{method:'POST',body:JSON.stringify({item_key})});export const getCompanions=()=>request<Companion[]>('/api/companions');export const getChat=()=>request<ChatMessage[]>('/api/chat');export const sendChat=(content:string,context:Record<string,unknown>={})=>request<ChatMessage>('/api/dm/chat',{method:'POST',body:JSON.stringify({content,context})});export const clearChat=()=>request<{ok:boolean}>('/api/chat',{method:'DELETE'});export async function uploadAvatar(file:File){const form=new FormData();form.append('file',file);return request<{avatar_url:string}>('/api/avatar',{method:'POST',body:form})}
export const createCharacter=(character:Omit<Character,'class'> & {'class':string})=>request<User>('/api/character',{method:'POST',body:JSON.stringify({name:character.name,race:character.race,character_class:character.class,background:character.background,...character.stats})});
export const deleteCharacter=()=>request<User>('/api/character',{method:'DELETE'});
export const getCharacterSheet=()=>request<DndSheet>('/api/character/sheet');
export const makeDndCheck=(skill:string,dc:number,advantage:-1|0|1=0)=>request<DndCheck>('/api/check',{method:'POST',body:JSON.stringify({skill,dc,advantage})});
export const rollDnd=(kind:'skill'|'save'|'attack'|'damage',key:string,target:number=15,advantage:-1|0|1=0)=>request<DndRoll>('/api/dnd/roll',{method:'POST',body:JSON.stringify({kind,key,target,advantage})});