import {FormEvent,useState} from 'react';
import {BookOpen,Shield,Swords} from 'lucide-react';
import {login,register} from './api';
import './auth.css';

export default function Auth({onAuth}:{onAuth:(user:any)=>void}){
 const [mode,setMode]=useState<'login'|'register'>('login');const [loginValue,setLoginValue]=useState('');const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 const submit=async(e:FormEvent)=>{e.preventDefault();setError('');setBusy(true);try{const u=mode==='login'?await login(loginValue,password):await register(loginValue,email,password);onAuth(u)}catch(err){setError(err instanceof Error?err.message:'Не удалось войти')}finally{setBusy(false)}};
 return <div className="auth-screen"><div className="auth-card"><div className="auth-emblem"><Swords/><span>DND ADVENTURE</span></div><div className="auth-divider"/><h1>{mode==='login'?'Вернуться в приключение':'Создать героя'}</h1><p>{mode==='login'?'Войди в аккаунт и продолжи свою хронику.':'Создай героя, получай опыт и записывай победы в хронику.'}</p><form onSubmit={submit}><input value={loginValue} onChange={e=>setLoginValue(e.target.value)} placeholder="Имя героя" autoComplete="username" required/>{mode==='register'&&<input value={email} onChange={e=>setEmail(e.target.value)} type="email" placeholder="Email" autoComplete="email" required/>}<input value={password} onChange={e=>setPassword(e.target.value)} type="password" placeholder="Пароль (минимум 8 символов)" autoComplete={mode==='login'?'current-password':'new-password'} minLength={8} required/>{error&&<div className="auth-error">{error}</div>}<button className="primary" disabled={busy}>{busy?'ОТКРЫВАЕМ ВРАТА...':mode==='login'?'ВОЙТИ В ПРИКЛЮЧЕНИЕ':'СОЗДАТЬ ГЕРОЯ'}</button></form><button className="link-btn" onClick={()=>{setMode(mode==='login'?'register':'login');setError('')}}>{mode==='login'?'Нет героя? Создать нового':'Уже есть герой? Войти'}</button><div className="auth-note"><Shield size={14}/><span>Прогресс, опыт и достижения сохраняются.</span><BookOpen size={14}/></div></div></div>
}
